### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by koendv** [LS80/tvheadend-recordings-import#1]
Thanks. Upgraded a tvheadend server, and forgot to save the logfile. This seems to be exactly what I need, except the script throws an error:

```
Traceback (most recent call last):
  File "/home/tvheadend/src/tvheadend-recordings-import/tvheadend-recordings-import.py", line 95, in <module>
    for recording_data in recordings(args.path, args.date_limit, args.output_path):
  File "/home/tvheadend/src/tvheadend-recordings-import/tvheadend-recordings-import.py", line 59, in recordings
    yield recording_data(
TypeError: 'str' object is not callable
```

**Comment by LS80** [comment]
What's the exact command you're running?

**Comment by koendv** [comment]
```
tvheadend@raspberrypi:~/src/tvheadend-recordings-import $ pipenv shell
(tvheadend-recordings-import) tvheadend@raspberrypi:~/src/tvheadend-recordings-import $ python3.8 --version
Python 3.8.9
(tvheadend-recordings-import) tvheadend@raspberrypi:~/src/tvheadend-recordings-import $ ./tvheadend-recordings-import.py --path /mnt/recordings/
Traceback (most recent call last):
  File "./tvheadend-recordings-import.py", line 95, in <module>
    for recording_data in recordings(args.path, args.date_limit, args.output_path):
  File "./tvheadend-recordings-import.py", line 59, in recordings
    yield recording_data(
TypeError: 'str' object is not callable
(tvheadend-recordings-import) tvheadend@raspberrypi:~/src/tvheadend-recordings-import $ 
```
Thanks for looking at this.

**Comment by koendv** [comment]
Could you tell me what version of python you are using? In the pipenv,
what is the output of 'pip3 list'?

best,
koen

**Comment by LS80** [comment]
It's been two years since I ran it. I'll see if I can reproduce the error...

**Comment by koendv** [comment]
Thanks for taking your time to solve this.
